const API_BASE="https://executive-engine-os.onrender.com";
let actions=JSON.parse(localStorage.getItem("ee_actions_v36300")||"null")||[
{id:"abc-roofing-proposal",title:"ABC Roofing Proposal",subtitle:"Proposal draft ready for review",priority:"High",due:"Due today",age:"2h ago",category:"proposal",thread:[]},
{id:"bob-meeting-strategy",title:"Bob Meeting – Strategy",subtitle:"Strategic planning meeting",priority:"High",due:"Today 3:00 PM",age:"1h ago",category:"meeting",thread:[]},
{id:"auto-loan-leads-followup",title:"Auto Loan Leads Follow-Up",subtitle:"3 follow-ups pending response",priority:"Medium",due:"Due tomorrow",age:"4h ago",category:"follow_up",thread:[]},
{id:"q4-sales-push",title:"Q4 Sales Push Strategy",subtitle:"Strategy draft in progress",priority:"Low",due:"Due in 2 days",age:"6h ago",category:"strategy",thread:[]},
{id:"investor-followup",title:"Investor Follow-Up",subtitle:"Update deck and follow up",priority:"Low",due:"Due in 3 days",age:"1d ago",category:"follow_up",thread:[]},
{id:"website-redesign",title:"Website Redesign",subtitle:"Gather requirements",priority:"Low",due:"Due in 1 week",age:"2d ago",category:"documents",thread:[]}];
let activeActionId=localStorage.getItem("ee_active_action_v36300")||null;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("ee_actions_v36300",JSON.stringify(actions));if(activeActionId)localStorage.setItem("ee_active_action_v36300",activeActionId)}
function level(p){return(p||"Low").toLowerCase()} function active(){return actions.find(a=>a.id===activeActionId)}
function renderActions(){const q=($("actionSearch").value||"").toLowerCase();const f=actions.filter(a=>(a.title+" "+a.subtitle+" "+a.priority).toLowerCase().includes(q));$("actionsRail").innerHTML=f.map(a=>`<div class="action-card ${level(a.priority)} ${a.id===activeActionId?"active":""}" onclick="openAction('${a.id}')"><div class="action-top"><div><strong>${esc(a.title)}</strong><span>${esc(a.subtitle)}</span></div><em class="badge ${level(a.priority)}">${esc(a.priority)}</em></div><div class="action-time"><span>${esc(a.due)}</span><span>${esc(a.age)}</span></div></div>`).join("");$("notificationCount").textContent=actions.length}
function openAction(id){activeActionId=id;let a=active();if(a&&(!a.thread||!a.thread.length)){a.thread=[{role:"assistant",response:{what_matters:a.subtitle,next_move:"Review this ACTION and decide the next operational move.",why_it_matters:"Keeping this in one thread prevents scattered notes and missed follow-up.",risk:"This can stall if the next step is not clear.",recommended_actions:["Review context","Update draft","Close follow-up"],missing_info:[],draft:`${a.title}\n\nWhat matters:\n${a.subtitle}\n\nNext move:\nReview this ACTION and continue the thread.`}}]}save();renderActions();renderThread()}
function renderThread(){const feed=$("threadFeed");const a=active();if(!a){feed.innerHTML=`<div class="empty-thread"><div class="section-label">OPERATING THREAD</div><h3>Responses will appear here in order.</h3><p>Use The Engine above. Every response becomes an ACTION thread with next move, risk, recommendations, and editable detail.</p></div>`;return}feed.innerHTML=`<div class="empty-thread"><div class="section-label">ACTION THREAD</div><h3>${esc(a.title)}</h3><p>${esc(a.subtitle)}</p></div>${(a.thread||[]).map((m,i)=>renderMsg(m,i)).join("")}`}
function renderMsg(m,i){if(m.role==="user")return`<div class="user-card-thread"><p>${esc(m.content)}</p></div>`;const r=m.response||{},id=`detail-${i}`;return`<div class="assistant-card"><div class="msg-kicker">EXECUTIVE RESPONSE</div><h3>${esc(r.what_matters||"ACTION organized.")}</h3><div class="exec-grid"><div class="exec-row"><div class="exec-label">WHAT MATTERS</div><div class="exec-value">${esc(r.what_matters||"")}</div></div><div class="exec-row"><div class="exec-label">NEXT MOVE</div><div class="exec-value">${esc(r.next_move||"")}</div></div><div class="exec-row"><div class="exec-label">WHY IT MATTERS</div><div class="exec-value">${esc(r.why_it_matters||"")}</div></div><div class="exec-row"><div class="exec-label">RISKS</div><ul class="exec-list"><li>${esc(r.risk||"No major risk detected.")}</li></ul></div><div class="exec-row"><div class="exec-label">RECOMMENDED ACTIONS</div><ul class="exec-list">${(r.recommended_actions||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></div><button class="expand-btn" onclick="toggleDetail('${id}')">View Detailed Brief</button></div><div class="detail-card" id="${id}"><div class="msg-kicker">DETAILED BRIEF</div><p><strong>Missing info:</strong> ${esc((r.missing_info||[]).join(", ")||"Nothing obvious.")}</p><textarea id="draft-${i}">${esc(r.draft||"")}</textarea><div class="detail-actions"><button class="small-btn" onclick="editDraft(${i},'polish')">AI Polish</button><button class="small-btn" onclick="editDraft(${i},'client')">Client Ready</button><button class="small-btn" onclick="editDraft(${i},'shorten')">Shorten</button><button class="small-btn" onclick="editDraft(${i},'followup')">Follow-Up</button><button class="small-btn" onclick="editDraft(${i},'proposal')">Proposal</button></div></div>`}
async function runCommand(){const input=$("commandInput").value.trim();if(!input)return;let a=active();if(!a){a={id:"action-"+Date.now(),title:makeTitle(input),subtitle:"Generated from The Engine",priority:detectPriority(input),due:"New",age:"just now",category:detectCategory(input),thread:[]};actions.unshift(a);activeActionId=a.id}a.thread.push({role:"user",content:input});$("commandInput").value="";save();renderActions();renderThread();let response=localResponse(input,a.category);try{const res=await fetch(API_BASE+"/engine-operate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input,action_id:a.id,title:a.title,category:a.category})});const data=await res.json();if(data&&data.short){response={what_matters:data.short.what_matters,next_move:data.short.next_move,why_it_matters:data.why_it_matters,risk:data.short.risk,recommended_actions:data.recommended_actions||[],missing_info:data.missing_info||[],draft:data.draft||""};a.title=data.title||a.title;a.category=data.category||a.category;a.priority=data.priority||a.priority}}catch(e){}a.subtitle=response.what_matters||a.subtitle;a.age="just now";a.thread.push({role:"assistant",response});save();renderActions();renderThread();setTimeout(()=>{$("threadFeed").lastElementChild?.scrollIntoView({behavior:"smooth",block:"end"})},60)}
function localResponse(input,cat){cat=cat||detectCategory(input);let r={what_matters:"This is now an active ACTION. The context is captured and organized.",next_move:"Clarify the next decision, owner, and deadline.",why_it_matters:"Execution improves when loose thoughts become one organized thread with next steps and follow-up.",risk:"This can stall if it remains a loose note with no owner, due date, or output.",recommended_actions:["Confirm the objective.","Define the next move.","Create the needed draft or follow-up."],missing_info:[]};if(cat==="meeting"){r.what_matters="Meeting signal detected. This needs prep, talking points, and a follow-up path.";r.next_move="Prepare the meeting brief and decide what must be confirmed before the meeting ends.";r.why_it_matters="The value of the meeting is created by the next step, not the conversation itself.";r.risk="The meeting may create motion but no result if budget, decision-maker, or follow-up is not confirmed.";r.recommended_actions=["Prepare 3 talking points.","Identify what decision is needed.","Draft the follow-up before the meeting."]}if(cat==="proposal"){r.what_matters="Proposal opportunity detected. Scope and pricing need to be shaped before this becomes client-ready.";r.next_move="Build the proposal overview and identify missing pricing, scope, timeline, and decision details.";r.why_it_matters="Fast proposal structure increases close probability and prevents the opportunity from drifting.";r.risk="The proposal may become vague or underpriced if scope, timing, and success metrics are not confirmed.";r.recommended_actions=["Draft proposal overview.","List missing scope/pricing details.","Prepare client-ready next step."]}r.draft=`${makeTitle(input)}\n\nWHAT MATTERS\n${r.what_matters}\n\nNEXT MOVE\n${r.next_move}\n\nRECOMMENDED ACTIONS\n- ${r.recommended_actions.join("\n- ")}`;return r}
function editDraft(i,type){const el=$(`draft-${i}`);if(!el)return;if(type==="shorten")el.value=el.value.split("\n").filter(Boolean).slice(0,8).join("\n");else if(type==="client")el.value="CLIENT-READY VERSION\n\n"+el.value+"\n\nNext Step:\nPlease confirm the preferred direction, timing, and scope.";else if(type==="followup")el.value+="\n\nFOLLOW-UP DRAFT\nThanks for the conversation. I’ll prepare the next-step overview and send a clear direction with recommended actions, timing, and scope.";else if(type==="proposal")el.value+="\n\nPROPOSAL STRUCTURE\n- Problem\n- Recommended scope\n- Timeline\n- Investment range\n- Next step";else el.value+="\n\nPOLISH NOTES\n- Make this clearer.\n- Confirm owner, deadline, and next step.\n- Remove vague language."}
function toggleDetail(id){$(id)?.classList.toggle("show")}function makeTitle(input){const t=input.toLowerCase();if(t.includes("bob")&&(t.includes("auto")||t.includes("loan")))return"Bob — Auto Loan Strategy";if(t.includes("proposal"))return"Proposal — "+input.split(/\s+/).slice(0,4).join(" ");if(t.includes("meeting"))return"Meeting — "+input.split(/\s+/).slice(0,5).join(" ");return input.split(/\s+/).slice(0,6).join(" ")||"New Action"}function detectCategory(input){const t=input.toLowerCase();if(t.includes("meeting")||t.includes("met with"))return"meeting";if(t.includes("proposal"))return"proposal";if(t.includes("follow"))return"follow_up";if(t.includes("strategy")||t.includes("marketing")||t.includes("sales")||t.includes("ads"))return"strategy";return"action"}function detectPriority(input){const t=input.toLowerCase();if(["urgent","proposal","client","meeting","revenue","today"].some(x=>t.includes(x)))return"High";if(["follow","strategy","task"].some(x=>t.includes(x)))return"Medium";return"Low"}function esc(str){return String(str||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
async function health(){try{const res=await fetch(API_BASE+"/health",{cache:"no-store"});const data=await res.json();$("backendStatus").textContent=data.status==="ok"?"Backend Online":"Backend Check";$("backendStatus").classList.toggle("online",data.status==="ok")}catch(e){$("backendStatus").textContent="Backend Offline"}}
document.addEventListener("DOMContentLoaded",()=>{$("runCommand").addEventListener("click",runCommand);$("commandInput").addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")runCommand()});$("actionSearch").addEventListener("input",renderActions);$("viewAllActions").addEventListener("click",()=>{activeActionId=null;localStorage.removeItem("ee_active_action_v36300");renderActions();renderThread()});renderActions();renderThread();health()});
