const API_URL = window.EXECUTIVE_ENGINE_API_URL || 'https://executive-engine-os.onrender.com';
const $ = (id)=>document.getElementById(id);
const state = {
  activeView:'command',
  entries: JSON.parse(localStorage.getItem('ee_entries')||'[]'),
  latest:null,
  lists:{
    priorityActions:['Finalize Ontario auto loan proposal|Due today','Approve Google Ads budget|Due today','Review landing page wireframes|Due tomorrow'],
    nextMoves:['Keyword research & grouping|Due today','Competitor ad analysis|Due tomorrow','CPA tracking setup|Due tomorrow'],
    activeWorkflows:['Ontario Auto Loan Proposal|In progress','Q2 Marketing Strategy|In progress','Investor Meeting Prep|In progress'],
    industryAlerts:['Auto loan demand up 14% in Ontario this month','Google Ads CPA benchmarks in auto finance decreased 8%','New compliance update affecting lending disclosures'],
    opportunities:['Expand targeting to nearby regions','Retarget recent website visitors with ads','Optimize ad copy for lower CPA'],
    risksMonitor:['Rising cost per lead in auto finance','Competitor increasing brand visibility','Economic indicators affecting loan approvals'],
    insightsFeed:['Top performing keywords this week','Landing page conversion rate improved 12%','Ad spend efficiency up 9%']
  }
};
function save(){localStorage.setItem('ee_entries', JSON.stringify(state.entries.slice(0,50)));}
function detectCategory(text){const t=text.toLowerCase();const rules=[['Meeting',['meeting','agenda','talking points','client call','investor','prep']],['Proposal',['proposal','pitch','quote','pricing','offer','scope']],['Decision',['decide','decision','choose','tradeoff','should i','option']],['Risk',['risk','problem','blocker','threat','issue','concern','compliance']],['Execution',['build','execute','launch','implement','fix','deploy','workflow']],['Strategy',['strategy','growth','market','positioning','revenue','seo','ads','cpa']]];for(const [cat,words] of rules){if(words.some(w=>t.includes(w)))return cat;}return 'General';}
function localResponse(input, cat){
  const t=input.toLowerCase();
  const weak=t.replace(/[^a-z0-9 ]/g,'').trim().length<5 || /^(wow+|lol+|haha+|a girl)$/i.test(t.trim());
  const status=/where is|where's|status|my proposal|find my|what happened/.test(t);
  const repair=/fix|bad|weak|same response|error|broken|not working/.test(t);
  const cognition=/executive engine|cognition infrastructure|\bee\b/.test(t);
  let category=cat;
  if(weak) category='Clarify';
  if(status) category='Execution';
  if(cognition) category='Strategy';
  let base={pressure:42,priority:'High'};
  if(weak){return {...base,category,pressure:18,priority:'Medium',executive_summary:'The input is too low-signal to create a trusted executive workflow.',strategic_diagnosis:'Executive Engine should not fake certainty from vague input. A trusted operating system asks for the missing objective instead of generating generic noise.',best_move:'Ask for the outcome, category, deadline, and desired output.',clear_answer:'The input is too low-signal to create a trusted executive workflow.\n\nStrategic diagnosis: Executive Engine should not fake certainty from vague input.\n\nBest move: Ask for the outcome, category, deadline, and desired output.',next_move:'Ask for the outcome, category, deadline, and desired output.',decision:'Do not create a fake workflow from unclear input.',action_steps:['Ask what outcome the user wants.','Ask whether this is a meeting, proposal, decision, risk, strategy, or execution task.','Ask whether there is a deadline or pressure point.','Wait for a real command before generating assets.'],ready_assets:['Clarifying prompt','Category selector','Outcome capture'],risk:['Fake confidence from vague input.','Wrong category selection.','Canned response behavior.'],push_intelligence:['Request clearer command','Hold workflow creation','Protect response quality'],recommended_command:'Clarify the objective, category, deadline, and desired output.'};}
  if(status){return {...base,category:'Execution',pressure:58,executive_summary:'This is a workflow-status request, not a request for another generic proposal.',strategic_diagnosis:'The system must show whether the proposal asset exists, whether it was saved, and what the next recovery action is. If persistence is not connected, regenerate the proposal and attach it to an active workflow.',best_move:'Recover or regenerate the proposal package and create a visible asset record.',clear_answer:'This is a workflow-status request, not a request for another generic proposal.\n\nStrategic diagnosis: The system must show whether the proposal asset exists and what the next recovery action is.\n\nBest move: Recover or regenerate the proposal package and create a visible asset record.',next_move:'Recover or regenerate the proposal package and create a visible asset record.',decision:'Treat this as workflow continuity failure, not content generation.',action_steps:['Check the latest active workflow for a saved proposal asset.','If no asset exists, regenerate the proposal package from the last known objective.','Create a visible asset record with status, created time, owner, and next action.','Change future status questions to retrieve the asset instead of repeating a template.'],ready_assets:['Proposal status card','Draft proposal package','Asset persistence record','Open workflow detail'],risk:['Executive trust drops if generated work cannot be found later.','Repeated templates make the system feel fake.','No persistence makes each session behave like a reset.'],push_intelligence:['Recover proposal asset','Create proposal status workflow','Add asset retrieval path'],recommended_command:'Open the latest active workflow and return asset status, draft state, owner, and next action.'};}
  if(cognition){return {...base,category:'Strategy',pressure:46,executive_summary:'Yes — this moves Executive Engine closer to Executive Cognition Infrastructure if it improves intent, continuity, anticipation, and operational leverage.',strategic_diagnosis:'The moat is not the interface. The moat is executive state management: pressure, priorities, decisions, workflows, assets, memory, and next moves.',best_move:'Prioritize the response intelligence engine before adding more UI.',clear_answer:'Yes — this moves Executive Engine closer to Executive Cognition Infrastructure if it improves intent, continuity, anticipation, and operational leverage.\n\nStrategic diagnosis: The moat is executive state management.\n\nBest move: Prioritize the response intelligence engine before adding more UI.',next_move:'Prioritize the response intelligence engine before adding more UI.',decision:'Promote backend intelligence quality as the immediate priority. Hold layout changes unless blocked.',action_steps:['Replace canned category responses with real intent analysis.','Add clarification handling for low-signal inputs.','Differentiate proposal, meeting, decision, risk, execution, and strategy outputs.','Add status-response behavior for commands like where is my proposal.','Preserve the existing layout while improving the system brain.'],ready_assets:['Executive Response Intelligence Engine','Intent classifier','Status response path','Mode-specific output contracts','Regression test prompts'],risk:['More frontend work will not fix weak cognition.','Static templates destroy executive trust.','Without continuity, the system cannot feel like an operating layer.'],push_intelligence:['Build V36180 brain patch','Test weak-input commands','Verify non-redundant responses'],recommended_command:'Build V36180 response engine and verify non-redundant outputs.'};}
  if(category==='Proposal'||/proposal|dealership|seo|google ads|cpa|auto loan/.test(t)){return {...base,category:'Proposal',pressure:52,executive_summary:'Build the proposal around one executive outcome: predictable qualified auto-loan applications at a controlled acquisition cost.',strategic_diagnosis:'The dealership does not need a marketing menu. It needs a revenue system: high-intent traffic, trust-building landing pages, conversion tracking, lead qualification, and weekly CPA control.',best_move:'Package the proposal as a 30-day acquisition sprint with a clear target: qualified finance applications under the CPA ceiling.',clear_answer:'Build the proposal around one executive outcome: predictable qualified auto-loan applications at a controlled acquisition cost.\n\nStrategic diagnosis: The dealership needs a revenue system, not a marketing menu.\n\nBest move: Package the proposal as a 30-day acquisition sprint.',next_move:'Package the proposal as a 30-day acquisition sprint.',decision:'Proceed with a focused revenue proposal tied to lead quality and CPA control.',action_steps:['Define the offer for bad credit, newcomers, self-employed buyers, trade-ins, and urgent approvals.','Create landing-page tracks for bad credit auto loans, fast approval, and dealership financing by city.','Build Google Ads around local intent, approval urgency, and finance keywords.','Install conversion tracking for forms, calls, appointments, and qualified applications.','Set CPA control rules: negatives, match types, weekly search-term review, and budget shifts.'],ready_assets:['Executive proposal draft','30-day launch plan','Keyword and landing-page map','CPA control checklist','Client follow-up email'],risk:['Broad-match spend can inflate CPA.','Weak landing-page proof can suppress conversion.','Slow sales follow-up can waste qualified leads.'],push_intelligence:['Draft proposal package','Build CPA control plan','Prepare client-ready executive summary'],recommended_command:'Create the full proposal package with executive summary, offer, scope, 30-day plan, risks, pricing assumptions, and follow-up email.'};}
  if(repair){return {...base,category:'Execution',pressure:56,executive_summary:'This is a defect correction workflow: protect the working layout and replace the weak logic without creating a new design regression.',strategic_diagnosis:'The UI is functioning, but the intelligence layer is returning static or weak outputs. That is a response-engine issue, not a visual redesign issue.',best_move:'Ship a backend/logic-focused patch with a narrow test checklist and no layout changes.',clear_answer:'This is a defect correction workflow: protect the working layout and replace the weak logic.\n\nStrategic diagnosis: This is a response-engine issue, not a visual redesign issue.\n\nBest move: Ship a backend/logic-focused patch.',next_move:'Ship a backend/logic-focused patch.',decision:'Lock stable UI, upgrade response intelligence, test, package, deploy, verify.',action_steps:['Lock frontend layout and route contracts.','Identify the exact failure from the command.','Change only the response logic required to solve it.','Run test commands that prove outputs changed meaningfully.','Package the result as a versioned ZIP.'],ready_assets:['Versioned build ZIP','Backend response test report','Rollback note','Verification checklist'],risk:['Scope creep creates a new regression.','Frontend changes hide the backend issue.','No test report allows the canned response problem to return.'],push_intelligence:['Lock layout','Patch response engine','Run regression test'],recommended_command:'Build the next versioned implementation package with test checklist and rollback notes.'};}
  return {...base,category,executive_summary:'Executive Engine should convert this command into operational movement: what matters, what to do next, what asset is needed, what risk exists, and what follow-up keeps momentum alive.',strategic_diagnosis:'The request needs to be routed into a workflow category before the system can generate the right operating output.',best_move:'Clarify the business objective and create the first executable asset.',clear_answer:'Executive Engine should convert this command into operational movement.\n\nStrategic diagnosis: Route the request into the right workflow before generating output.\n\nBest move: Clarify the business objective and create the first executable asset.',next_move:'Clarify the business objective and create the first executable asset.',decision:'Route this into the highest-fit workflow and generate movement, not commentary.',action_steps:['Identify the intended outcome.','Select the correct workflow category.','Generate the first operational next move.','Create or update the relevant asset.','Set the follow-up command that maintains continuity.'],ready_assets:['Executive summary','Action sequence','Ready asset','Follow-up command'],risk:['Generic answer instead of operational output.','No asset created.','No continuity after response.'],push_intelligence:['Classify workflow','Create first asset','Maintain operating thread'],recommended_command:'Route this command into the correct executive workflow and create the first ready asset.'};
}
async function execute(){const input=$('commandInput').value.trim();if(!input)return;let cat=$('categorySelect').value;if(cat==='Auto select'){cat=detectCategory(input);$('categorySelect').value=cat;}let data;try{const r=await fetch(`${API_URL}/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input,category:cat,mode:cat.toLowerCase()})});if(!r.ok)throw new Error('bad');data=await r.json();}catch(e){data=localResponse(input,cat);}data.category=data.category||cat;const entry={input,category:data.category,created_at:new Date().toLocaleString(),response:data};state.entries.unshift(entry);state.latest=entry;save();$('commandInput').value='';renderAll();}
function renderThread(){const thread=$('thread');if(!state.entries.length){thread.innerHTML='<div class="msg"><h4>System Ready</h4><p>Enter a command to create the first operating thread.</p></div>';return;}thread.innerHTML=state.entries.map((e,i)=>{const r=e.response;return `<div class="pair"><div class="bubble-icon">♙</div><div class="msg user"><span class="tag">${e.category}</span><h4>User Input</h4><p>${escapeHtml(e.input)}</p><small>${e.created_at} • ${e.category}</small></div><div class="bubble-icon system">▰</div><div class="msg system"><h4>System Response</h4><b>Executive Summary</b><p>${escapeHtml(r.executive_summary||r.clear_answer||'')}</p>${r.strategic_diagnosis?`<b>Strategic Diagnosis</b><p>${escapeHtml(r.strategic_diagnosis)}</p>`:''}${r.best_move||r.next_move?`<b>Best Move</b><p>${escapeHtml(r.best_move||r.next_move)}</p>`:''}<b>Next Steps</b><ul>${(r.action_steps||[]).map(a=>`<li>◎ ${escapeHtml(a)}</li>`).join('')}</ul><small>${e.created_at} • ${e.category}</small><button class="viewDetail" onclick="openEntry(${i})">View Full Detail</button><div style="clear:both"></div></div></div>`}).join('');}
function renderLists(){Object.entries(state.lists).forEach(([id,arr])=>{const el=$(id);if(!el)return;el.innerHTML=arr.map(x=>{const [a,b]=x.split('|');return `<li onclick="toggleDone(this)">${escapeHtml(a)}${b?`<br><small>${escapeHtml(b)}</small>`:''}</li>`}).join('');}); if(state.latest){const r=state.latest.response;$('priorityActions').innerHTML=(r.action_steps||[]).slice(0,3).map(x=>`<li onclick="toggleDone(this)">${escapeHtml(x)}<br><small>Due today</small></li>`).join('');$('nextMoves').innerHTML=(r.push_intelligence||[]).slice(0,3).map(x=>`<li onclick="toggleDone(this)">${escapeHtml(x)}<br><small>Due tomorrow</small></li>`).join('');$('risksMonitor').innerHTML=(r.risk||r.risks||[]).slice(0,3).map(x=>`<li onclick="toggleDone(this)">${escapeHtml(x)}</li>`).join('');$('pressureScore').textContent=r.pressure||22;$('pressureLabel').textContent=(r.pressure||22)>35?'High':'Medium';}}
function renderView(view){state.activeView=view;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const title=view==='command'?'Command Centre':view.replace(/\b\w/g,c=>c.toUpperCase()).replace('Workflows','Active Workflows').replace('Knowledge','Knowledge Base');$('pageTitle').textContent=title;if(view!=='command'){openPanel(title, getViewContent(view));}}
function getViewContent(view){const map={workflows:state.lists.activeWorkflows,meetings:['Investor Meeting Prep|Tomorrow','Client Strategy Call|Friday','Internal Ops Review|Monday'],proposals:['Ontario Auto Loan Proposal|Active','Q2 Growth Proposal|Draft','Partnership Proposal|Review'],decisions:['Backend-only intelligence fix|Recommended','Frontend layout lock|Approved','Memory system timing|Delay'],risks:state.lists.risksMonitor,calendar:['Today: proposal build checkpoint','Tomorrow: investor prep','Friday: campaign review'],contacts:['Key client stakeholder','Developer contact','Marketing partner'],knowledge:['System Governance Documents','Executive Operating Logic Spec','Frontend Architecture Spec'],reports:['Execution tracker','Pressure summary','Workflow report'],settings:['API URL configured','Local storage enabled','Version lock active']};return map[view]||[];}
function openPanel(title, items){$('modalTitle').textContent=title;$('modalBody').innerHTML=`<ul>${items.map(x=>`<li>${escapeHtml(String(x).replace('|',' — '))}</li>`).join('')}</ul>`;$('modal').classList.remove('hidden');}
function openEntry(i){const e=state.entries[i];const r=e.response;$('modalTitle').textContent='Full Executive Detail';$('modalBody').innerHTML=`<h4>User Input</h4><p>${escapeHtml(e.input)}</p><h4>Next Move</h4><p>${escapeHtml(r.next_move||'')}</p><h4>Decision</h4><p>${escapeHtml(r.decision||'')}</p><h4>Ready Assets</h4><ul>${(r.ready_assets||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><h4>Risks</h4><ul>${(r.risk||r.risks||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><h4>Recommended Command</h4><p>${escapeHtml(r.recommended_command||'')}</p>`;$('modal').classList.remove('hidden');}
function toggleDone(el){el.classList.toggle('done');updateMetrics();}
function updateMetrics(){const done=document.querySelectorAll('.mini li.done').length;$('doneCount').textContent=8+done;$('progressCount').textContent=Math.max(0,12-done);$('completionRate').textContent=Math.min(99,62+done*3)+'%';}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderAll(){renderThread();renderLists();}
$('executeBtn').onclick=execute;$('commandInput').addEventListener('input',e=>{if($('categorySelect').value==='Auto select'){const cat=detectCategory(e.target.value);if(cat!=='General')$('categorySelect').value=cat;}});$('commandInput').addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter')execute();});$('clearBtn').onclick=()=>{$('commandInput').value='';$('categorySelect').value='Auto select';};$('filterBtn').onclick=()=>{const cats=[...new Set(state.entries.map(e=>e.category))];openPanel('Filter Command Thread',cats.length?cats:['No categories yet']);};$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state.entries,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='executive-engine-thread-export.json';a.click();};$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.add('hidden');};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>renderView(b.dataset.view));document.querySelectorAll('.panelBtn').forEach(b=>b.onclick=()=>openPanel(b.textContent.replace('›',''), state.lists[b.dataset.panel]||['Tracker opens latest execution metrics','Tasks completed today: '+$('doneCount').textContent,'Completion rate: '+$('completionRate').textContent]));$('profileBtn').onclick=()=>openPanel('Executive Profile',['Will Smith — Executive','Command OS active','Pressure tracking enabled','Local workflow persistence enabled']);
renderAll();
