create table if not exists public.items (
  id bigint generated by default as identity primary key,
  input text,
  mode text,
  decision text,
  next_move text,
  actions jsonb,
  risk text,
  priority text,
  created_at timestamptz default now()
);

alter table public.items enable row level security;

drop policy if exists "service role full access" on public.items;

create policy "service role full access"
on public.items
for all
using (true)
with check (true);
